source = base.conf # for $mainMod

$term = foot
$browser = brave --enable-features=UseOzonePlatform --ozone-platform=wayland
$filemanager = nautilus
$launcher = fuzzel
$screenshot = screenshot region

bind = $mainMod, T, exec, $term
bind = $mainMod, B, exec, $browser
bind = $mainMod, F, exec, $filemanager
bind = $mainMod, O, exec, $launcher
bind = $mainMod, P, exec, $screenshot
