source = base.conf

$lockScreen = nwg-lock

bind = $mainMod, L, exec, $lockScreen
bind = $mainMod SHIFT, C, exec, hyprctl reload      
bind = $mainMod SHIFT, M, exec, shutdown now
bind = $mainMod SHIFT, N, exec, reboot
